### ISSUE TITLE
Blind Cave Bear overpopulation

### ISSUE THREAD

**Issue by VallenFrostweaver** [RayTrace082/untamedwilds#10]
Minecraft 1.16.5
Forge 36.1.2
Untamed Wild 1.1.0

Blind Cave Bear population is way to high. This is not modified with the default configs. In the attached image I can count 18 of them in this one area and I've seen it in multiple areas. I am using Yung's Caves and other mods as well in this example.
![2021-06-03_11 05 51](https://user-images.githubusercontent.com/13642054/120627964-17302a80-c45c-11eb-86e9-0d16e96dd2e9.png)

**Comment by VallenFrostweaver** [comment]
Just to reinforce that there is an issue: 
![2021-06-03_11 14 44](https://user-images.githubusercontent.com/13642054/120629095-5dd25480-c45d-11eb-8609-1eb81d057911.png)

**Comment by RayTrace082** [comment]
Thanks for the report, this really needs to be fixed

The base parameters were tuned for vanilla cave generation, and since caves are cluttered and (relatively) narrow, I used a really generous distribution to ensure good spawning
I am very sure that, in a past version, YUNG's caves and Quark's Large caves were not considered valid caves for spawning my mobs, so something on my end or theirs has probably changed at some point, leading to this result

I have toned down their frequency to a less generous amount, added some explicit compatibility with YUNG's caves (chance is reduced by 2/3rds) and exposed the probability in the Config to give some more control of Underground mob frequency

Issue will be closed as I push the next update

**Comment by Cixon** [comment]
@RayTrace082 perhaps you could also add cross compatibility for [Caves & Cliffs Backport](https://www.curseforge.com/minecraft/mc-mods/caves-and-cliffs-backport) as well please? I know blackgear personally and his mods are great and popular! Your cave bears blend perfect with his mod but I suffer the same issue where they spawn crazy there as well.

**Biomes:**
`cavebiomes:caves` `cavesandcliffs:dripstone_caves` `cavesandcliffs:lush_caves`

**Comment by Cixon** [comment]
Also I spoke to the modder of [Adaptive performance tweaks](https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks) briefly about untamedwilds to add compatibility for the spawn rate/cap for your entities. Which their mod specializes in adding spawn tweaks amongst other things to vanilla and popular mods and their entities but mentioned they won't released that version until the experimental flag is removed from untamed wilds.

Was wondering how long we could expect the flag to exist?
Github [here](https://github.com/MarkusBordihn/adaptive_performance_tweaks/issues/10)

**Comment by RayTrace082** [comment]
I am planning to remove the experimental flag with the next version (very soon™), as the mod *seems* to be stable enough, while I do have a couple breaking changes in the backburner, those will wait until 1.17 or whatever next major version change.

>add cross compatibility for Caves & Cliffs Backport as well please? 

Done, it works on the same logic as Better Caves, having either mod installed will reduce the Underground spawnrate

**Comment by Cixon** [comment]
> 
> 
> I am planning to remove the experimental flag with the next version (very soon™), as the mod _seems_ to be stable enough, while I do have a couple breaking changes in the backburner, those will wait until 1.17 or whatever next major version change.
> 
> > add cross compatibility for Caves & Cliffs Backport as well please?
> 
> Done, it works on the same logic as Better Caves, having either mod installed will reduce the Underground spawnrate

excellent! thank you so much.
