### ISSUE TITLE
[1.18.2] Mobs spawn on leaves

### ISSUE THREAD

**Issue by Peach774** [RayTrace082/untamedwilds#112]
**Describe the bug**
Leaves are not supposed to be spawnable blocks, but they are spawning on top of trees, which means the animal AI breaks down and they don't move because they have nowhere to go.

**Steps To Reproduce**
1. Create a new world (might require BoP since they add more tall trees)
2. Fly around in creative and find animals in trees doing nothing.

**Version (please complete the following information):**
 - Minecraft version: [1.18.2]
 - Version of the mod: [2.1.1]
 - Additional mods: [Might require BiomesOPlenty]

**Comment by RayTrace082** [comment]
>Leaves are not supposed to be spawnable blocks

Leaves are spawnable blocks, otherwise Jungles (or densely vegetated biomes from mobs) would be barren

Every mob (or pack thereof) that spawns on top a tree is a mob that would, otherwise, not have spawned. I will be adding a config option so you can fine-tune this behavior (or just disable this) in the next version, but it's intended, even if it looks bad

**Comment by RayTrace082** [comment]
I have toned down heavily the leeway mobs get when spawning, so there should be no more mobs on top of trees, but can be replicated with the "treeSpawnBias" parameter in the Config file

**Comment by ghost** [comment]
I am getting this exact issue on the latest 1.16.5 version (with BYG+Terraforged+DynamicTrees) and can't find the treeSpawnBias in the config file. Did you only add that for 1.18?
