### ISSUE TITLE
Crash untamedwilds-1.18.2-2.1.2

### ISSUE THREAD

**Issue by BlackAures1** [RayTrace082/untamedwilds#127]
**Describe the bug**
Crash for unknown reasons. It was just a lightning strike. The crash report only mentions untamedwilds.world.gen.feature.FeatureCritterBurrow@68f0f3b5

**Crash Log**
All details here
[message (16).txt](https://github.com/RayTrace082/untamedwilds/files/8487075/message.16.txt)

**Comment by Daihok41** [comment]
Also get this crash with the critter burrow

**Comment by RayTrace082** [comment]
I cannot, for the life of me, replicate this problem in a dev environment (so I could get an extended stacktrace). I suspect it's due to trying to simultaneously generate a Burrow and another mod's structure at the same time, but its only a guess

Can a world affected by this crash load after the fact? If not, could you provide a world file so I can replicate it?

**Comment by RayTrace082** [comment]
The new version has added a few changes to burrow generator that **should** fix this issue, will close the issue in about a week if no further issues arise, but again, never managed to replicate this
