### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by DigitalWendigo** [RayTrace082/untamedwilds#140]
This is not a bug nor a suggestion. 
I'm playing on the last 1.16.5 beta upate and I can not, for the life of me, figure this mod out. 
I tried in a creative test world before moving on to a survival environment and while in creative, I am able to tame babies only that have been spawned by right-clicking a spawn egg on a parent. 
They don't seem to produce offspring on their own no matter how much time has passed in game. (Default configurations without any changes to breeding)
I've set them up in a test environment, fenced in, male and female. They don't eat any dropped foods, but they do chase down some other animals that are being spawned in vian an egg. However, mating isn't initiated and no offspring is produced even after a solid 4 in-game day period. 
Baby animals that have spawned in the wild with their parent natrually while generating new chunks can't be tamed as no food is accepted by them. 

I might be missing something, but I can not for the life of me figure out how this all works. 
Is there a wiki that can give better documentation?
How does one get a baby to spawn from wild parents that a player has managed to fence in?

**Comment by RayTrace082** [comment]
>How does one get a baby to spawn from wild parents that a player has managed to fence in?

For breeding to trigger, mobs need to have full HP, not be hungry and depending on the mob, be alone with their mate. If all conditions are fulfilled, they will mate, and the female will have babies once X days have passed (at most, 10 MC days, but depends on the species; 1 month of gestation in the real animal = 1 MC day by default). Your only way to know is with the Analyzer (Creative debug item), which will print that information.

Check out the config files, as there are a handful of options that will enable you to replicate vanilla behavior (favorite item triggering breeding mode, and babies instantly popping out instead of having to wait)

>Baby animals that have spawned in the wild with their parent natrually while generating new chunks

That's not from my mod. Don't know which mod does that, but depending on how it is handled, those babies may be missing NBT data to be functional (comes without saying, but don't report this as a bug in whatever mod does it, it's not)

Also, one of the latest 1.16 versions did fix a handful of issues where mobs could not recognize their favorite food

**Comment by DigitalWendigo** [comment]
> That's not from my mod. Don't know which mod does that, but depending on how it is handled, those babies may be missing NBT data to be functional (comes without saying, but don't report this as a bug in whatever mod does it, it's not)

To be fair I asumed it was a baby since it was incredibly small compared to the parent it was with. 
I didn't however check it with the analyzer during testing, which makes me thing it may not have been a baby but instead just incredibly small..? 
Is that a feature where they can spawn adults as baby-sized?
I have no mod installed that changes the spawning mechanics in any way. 
Untamed Wilds is entirely in control on that I'm afraid. 


> Check out the config files, as there are a handful of options that will enable you to replicate vanilla behavior (favorite item triggering breeding mode, and babies instantly popping out instead of having to wait)

I did try that, but hadn't had time to test it in a new world after changing. 
Will this change affect already present animals or does one have to make a new world and then test it on net entites for the configurations to take effect?

Also, thank you for replying on such short notice.

**Comment by DigitalWendigo** [comment]
Also will the analyzer eventually become an item one could make in survival? 
This could prove really useful for people that can't use things like Wayla or the one probe, or, implement the analyzer through crafttweaker.

**Comment by DigitalWendigo** [comment]
So to be absolutely sure... Could you confirm the things below?

easy_breeding = true
natural_breeding = false
gendered_breeding = false
player_breeding = true

With these settings, they should theoretically behave as vanilla animals do, correct? 
Meaning if I isolate two Hyenas in a fence, I should get a baby from it right?
Given I feed them rotten flesh?

**Comment by DigitalWendigo** [comment]
Alright I think I'm getting the hang of this all. 
But is it normal that when you right-click on a baby, you hear the feeding sound but no item is being used up during taming?
(I had rotten flesh and porkchop in my hotbar)
I fed the porkchop to the adults to make them breed, as they wouldn't accelt rotten flesh still. 
(Hyena)
But after they mated and produced 3 cubs at once, I proceeded to kill the adults and switched to survival moe for further testing. 
I had both feeding items in my inventory, the babies have been succesfully tamed as they now listen to commands, but none of the food items were actually removed from the hotbar during this process. Is this intended or a potential bug?

I'm terribly sorry if all this seems a bit annoying to deal with, but I have quite frankly no idea where else to ask this. 

Edit: I tested this with with my mods of choice installed, and I've tested it with just citadel and untamed wilds.

**Comment by RayTrace082** [comment]
>Is that a feature where they can spawn adults as baby-sized?

The math behind resizing mobs should make most mobs fall within reasonable bounds, but outliers can happen, and that's by choice. You *shouldn't* consistently see baby-sized mobs, but it's something that can rarely happen
(Some mobs have a custom baby model to prevent that issue, but Hyenas do not)

>Will this change affect already present animals

Yes. Only exception would be mobs that already bred before the config chance, since their "growingAge" will have been set before

>will the analyzer eventually become an item one could make in survival?

Not very likely, I don't think high-tech/goofy-magical content has a place in a wildlife mod outside of debugging. My intent is for players/modpack makers to make up a fitting CraftTweaker recipe for it based on the tech mods they have

>With these settings, they should theoretically behave as vanilla animals do, correct?

Yes, they should (but you still may want to change the "cycleLength" from 24000 (1 MC day) to a much lower value to shorten the cooldown between breeding and growing times, but only do this if you have disabled natural-breeding)
It will not be fully instant like it is in Vanilla, due to some AI issues I ran into (unlike Vanilla, the love task doesn't run every tick), so it may take them a tiny bit longer to breed 

>I had both feeding items in my inventory, the babies have been succesfully tamed as they now listen to commands, but none of the food items were actually removed from the hotbar during this process. Is this intended or a potential bug?

For the purposes of responding ASAP, it's a bug, and I am looking into it rn. Somehow, it's not reading correctly the favorite item, so it defaults to "nothing", meaning that the taming item, breeding tiem will be an empty hand (which can't be consumed). The intended item would be Rotten Flesh

It's failing to read global taming items, but works if they are defined at the species level (eg. bears). If you need, I can whip out a datapack that should probably fix this

>I'm terribly sorry if all this seems a bit annoying to deal with, but I have quite frankly no idea where else to ask this.

Don't worry, this is the place for these things

**Comment by DigitalWendigo** [comment]
The datapack would be a great help with this. 
I'm unfortunately incapable of making data packs myself
Again, thank you so much for such quick responses. It really clears a lot of things up. 

-Alright, but what of a different method for people to figure out what gender the animal is?
A mod called animania just added 'bits' for creatures like cows, just as an example. But obviously the udder was a clear sign already. Given in a situation a person has no way of getting the analyzer, how would they determine if both captured creatures are different genders? Given that of course Hyenas would be difficult to tell due to the whole 'fake' dangly bit. 
Edit: This mod of yours seems to aim towards real life logic by what I understand from it, yes? 
As such, you would theoretically just be able to tell what gender a specific mammal is by ovbious signs. 
I'll just exclude reptiles as those can be picked up and have their tooltip. 
But for mammals this might be a bit more difficult since they can't be picked up and inspected. 
Are there any future plans that would change this in any way or will it remain as it is now?

-The feeding and taming I'm getting better at understanding, but have noticed an interesting mechanic after trying it out with all the mentioned settings tweaked. 
When feeding two animals of the same species and undifined gender (for simplicity), they won't breed with each other even at full hunger, unless the player right-clicks them individually. 
Meaning if I right-click example A, it gains a glowing effect similar to how the bell makes enemies glow or the spectral arrow.
Right after that while the effect is applied, I have to do the same with example B and then they proceed to produce a baby. 
Is this intended as well? I only managed to figure it out after several tests as it isn't documented anywhere.

**Comment by Coolizzh** [comment]
How do i acces the config to change animal spawing?

**Comment by DigitalWendigo** [comment]
You need a specific software for that.  I recomend Notepad++

**Comment by Coolizzh** [comment]
Okay, I cant find the config to edit tough, if you dont mind could you type the pathway to it?

**Comment by DigitalWendigo** [comment]
appdata/roaming/.minecraft/config

**Comment by Coolizzh** [comment]
ah okay, I was messing around in the Untamedwilds folder, thanks!

**Comment by DigitalWendigo** [comment]
Wait did you open the .jar file?
You shouldn't open and edit those directly.

**Comment by Coolizzh** [comment]
Yeah i noticed, the game crashed. I re-downloaded it so its fixed

**Comment by Coolizzh** [comment]
I disabled the spawning of snakes since it caused the game to crash. however it seems to still be spawning because it just crashed again caused by snake. its on a server if it makes a diffrence

**Comment by DigitalWendigo** [comment]
I suggest opening a new issue for this and provide a mod list.
It could be another mod conflicting, and servers work a bit differently from singleplayer.

**Comment by Coolizzh** [comment]
Ah okay, willdo thanks

**Comment by RayTrace082** [comment]
>A mod called animania just added 'bits' for creatures like cows

Nope, not touching that topic with a 10ft pole. Manes and Horns are alright, but no schlongs nor milkers
The idea I just got would be to have some text display that information when the player looks at a mob through the Spyglass (or a new similar item), since it's not a very useful item, is immersive, and allows players to get that information from outside of mauling range

>they won't breed with each other even at full hunger, unless the player right-clicks them individually.

That's because you disabled "Natural Breeding", meaning that mobs will only breed when prompted to do so (btw, don't enable that option if you changed breeding requirements, since you can very easily end up with mobs reproducing at an exponential rate)

>if I right-click example A, it gains a glowing effect

That's an unrelated debug thing, and shouldn't happen in Survival mode. It's a way to highlight all mobs on the same 'pack/herd', if the mob has the capability to hunt in packs.

Attached is the datapack to fix Hyenas. And a plug for the OpenLoader mod, which has a much better way to load datapacks than the intended one.
[hyena_fixes.zip](https://github.com/RayTrace082/untamedwilds/files/8599215/hyena_fixes.zip)

**Comment by DigitalWendigo** [comment]
> Nope, not touching that topic with a 10ft pole. Manes and Horns are alright, but no schlongs nor milkers
> The idea I just got would be to have some text display that information when the player looks at a mob through the Spyglass (or a new similar item), since it's not a very useful item, is immersive, and allows players to get that information from outside of mauling range

I asume you mean the spyglass from 1.17/1.18? 
Would that mean that the updated file will only be available for that version or will 1.16.5 have something similar?
Obviously I wouldn't be suggesting any dangly bits to be added, but just something, anything, to help identify genders so as to not expext a baby by constantly feeding two males.
In this case, I really like your idea with the simple text. 


> That's because you disabled "Natural Breeding", meaning that mobs will only breed when prompted to do so (btw, don't enable that option if you changed breeding requirements, since you can very easily end up with mobs reproducing at an exponential rate)

Alright, got it. So the glowing and manualy selecing their breeding partner is a feature. Yeah the other option I won't be touching so as to avoid something similar as the bug with 300+ sharks. 


> That's an unrelated debug thing, and shouldn't happen in Survival mode. It's a way to highlight all mobs on the same 'pack/herd', if the mob has the capability to hunt in packs.

Ah, that's my bad, I'm sorry. I didn't test that part in survival since the hyenas were two-shotting me in survival which didn't allow me to fully test it even behind a fence. 
This happened in creative while I was figuring out how to make them produce ofspring manually. 

And thank you for the data pack! I really appreciate it. 
Thank you again for all your help. 
I also hope this conversation will be of help to anyone else who might have similar questions.
