### ISSUE TITLE
Improved Spawning 1.18

### ISSUE THREAD

**Issue by Tyrius1** [RayTrace082/untamedwilds#152]
Its not uncommon to find bison and other animals spawning in water. Due to how 1.18's biome placement is. Sometimes it says plains but the terrain is clearly a river or a large body of water. Animals will just spawn in the water in these instances. 

Could you add a check to prevent them from spawning in water?

**Comment by RayTrace082** [comment]
This is really simple to solve, but given the ridiculous amount of terrain that caves can end up taking, it'd mean a lot less overall mobs in the world

Given the request, I can add a config option to prevent non-amphibious mobs from spawning on water, but the default will stay as it is (the swimming AI should eventually take them to dry land, since it is now fixed)
