### ISSUE TITLE
Variants

### ISSUE THREAD

**Issue by Tyrius1** [RayTrace082/untamedwilds#157]
/summon untamedwilds:shark ~ ~ ~ {Variant:4}

Could you setup the variants so that they might be summoned using the above command?

I'd like to create a Great White Jaws Boss 😋

**Comment by RayTrace082** [comment]
I am 100% sure you can already do this

Just add {Size:1} (or whatever value you want) somewhere in the NBT, because for some stupid reason, the game defaults that value to zero (mob so tiny that it doesn't even render) instead of one (normal model size)

`/summon untamedwilds:shark ~ ~ ~ {Variant:4, Size:2}`

should work (for a bigger than normal GW Shark

**Comment by Tyrius1** [comment]
Eyyy that worked :) Thanks!

Any chance you could do something about the hitboxes not increasing in size when the mob is enlarged?
Anything above 2 is basically impossible to hit the hitbox

Side note, Megalodons would probably make this a moot point 😆

**Comment by RayTrace082** [comment]
Hitboxes are normally immutable, that is, you can't normally change it

It *can* be fixed with some funny code, and I plan to eventually do so, but it sounds like a massive pain to get the hitboxes to dynamically match with a mob's size without many bugs (not to mention that such changes would have to be accounted at many places by the AI)

**Comment by Tyrius1** [comment]
Roger that! Appreciate you!
