### ISSUE TITLE
Issue with **RandomPatches** mod.   Animals picked up are teleporting back to the original spot

### ISSUE THREAD

**Issue by MonoSyntax** [RayTrace082/untamedwilds#16]
When I pick up an animal and place it somewhere else it teleports back to its original spot.

I tested some mod combinations. to make sure. It looks like when I run RandomPatches and this mod together issue appears. 

*(Sorry for my english not my first language.)*

**Forge:**  36.1.32

**Used Mods:** Citadel / UntamedWilds 1.2.0 / RandomPatches 2.4.4

**Also This log appears:**
*[16:25:49] [Server thread/WARN] [minecraft/ServerWorld]: Trying to add entity with duplicated UUID a8a6d4da-0209-4af5-aa1c-f2162b92125f. Existing untamedwilds:tortoise#486, new: untamedwilds:tortoise#486*

**Comment by RayTrace082** [comment]
You can ignore the log, that's unrelated and on my end because Items were trying to spawn the same entity twice (it is harmless, as the second entity doesn't spawn, but it is fixed in-dev)

After some digging around, I have found that the conflict is between RandomPatches' solution for [MC-2025](https://bugs.mojang.com/browse/MC-2025), since they store the (precise) position of every entity and use it to place entities, which conflicts with some key assumptions I make when turning a mob into NBT data

It seems fixable, or at least can be worked around, but meanwhile, you can temporarily fix it by setting `fix_mc-2025 = true` to false in RandomPatches' config file

**Comment by MonoSyntax** [comment]
Thanks for the answer :)
Keep up the good work

**Comment by RayTrace082** [comment]
The bug is fixed on my end now, so you can safely re-enable RandomPatches' fix for MC-2025
