### ISSUE TITLE
Caging Rhinos make rhino die in some biomes

### ISSUE THREAD

**Issue by me6669** [RayTrace082/untamedwilds#18]
When i cage rhinos, they catch and show their data on the block when mined, but when placed back down and right clicked, no rhino appears, after more testing i noticed that it only spawns in savanna biome out of the ones i tested (plains and desert) it doesnt
steps to reproduce:
-install citadel and untamed wilds(no other mods)
-capture rhino
-mine rhino cage
-place cage in savanna(rhino spawns)
-place cage in plains(no rhino spawns)

**Comment by RayTrace082** [comment]
Shit, I have no clue how this one slipped by
Stored mobs were trying to spawn from zero, and if they succeeded, they had the previous NBT data applied. Thing is, if no Variant fits a biome, the spawn gets cancelled, so it never gets to apply NBT data

Fixed in-dev, issue will be closed as I push a hotfix
