### ISSUE TITLE
Large snakes and breeding; How do they do it?

### ISSUE THREAD

**Issue by Neverl0re** [RayTrace082/untamedwilds#187]
Hello! First off, I'd like to say that I absolutely love this mod. All the variation in the wildlife is very pleasing to me, And my friends on the server I play on are having a blast with it too. :) 

Now getting into the issue- How exactly does one get large snake eggs? I've got a pair consisting of a male and female reticulated python in a pen together, And I'm trying to get eggs, But I want to make sure I'm not making an ass of myself by missing out on some important factors or anything. 

The smaller snakes go absolutely wild with making eggs, I have a corn snake burrow in my home biome and they're breeding just fine there...Do the large snakes do this as well, Just slower? Do they need to eat first? And do they need to be alone in their pen, As an escapee softshell turtle has been living in there and will have to be evicted. Thanks in advance!

Edit; Side note, Sorry if I didn't tag anything right, This is my first time using Github. ": )

**Comment by RayTrace082** [comment]
The smaller snakes (and Tortoises/Turtles) were breeding like crazy, which has been corrected

For big snakes to breed, it should be enough by keeping two of opposite genders close and at full health, but keep in mind that there is about 7 minecraft days of pregnancy until the eggs are delivered

If you are on the latest 1.18 version, zoom into the female snake with the Spyglass (large snakes are finnicky, since only the "main" hitbox will display information, it should be halfway in the body of the snake), it should tell you if it is pregnant (no message if it's not), or use the Mob Analyzer (debug item only available in the creative tab)

**Comment by Neverl0re** [comment]
Ah thank you so much! We're currently using the 1.16.5 version, Since the server has a custom modpack with different things in it- But we have a Caves and Cliffs backport, So the spyglass is obtainable there. I'll try that, Thank you very much. :D 👍
