### ISSUE TITLE
Tortoise crashing server 

### ISSUE THREAD

**Issue by AngelTiramisu** [RayTrace082/untamedwilds#197]
**Describe the bug**
Player joins near Tortoise, server crashes 

**Crash Log**
If applicable, include a crash log through a text sharing service [eg. pastebin]

**Screenshots**

**Version (please complete the following information):**
 - Minecraft version: 1.18.2
 - Version of the mod: 1.18.2-2.2.0
[crash-2022-11-16_19.19.38-server.txt](https://github.com/RayTrace082/untamedwilds/files/10027554/crash-2022-11-16_19.19.38-server.txt)

**Comment by RayTrace082** [comment]
There's nothing in the code that could cause a mob's Variant to overflow, so I'd like to know more information. The only case that could cause this would be messing with NBT and/or datapacks in an existing world

Where does this crashing Tortoise come from? Did it spawn from a burrow, an Egg, is it a Tortoise you picked up and placed or did you take it from the Creative inventory? 

I'd like to know the source of the problem, but for what's worth, the next version already includes a failsafe where mobs with impossible NBT data get clamped back within bounds when loaded, but don't expect anything soon

**Comment by AngelTiramisu** [comment]
He has provided me with his crash log
https://paste.ee/p/JRdZ9

**Comment by RayTrace082** [comment]
Does it crash on load-in, or did it only happen once? Is the Burrows config option enabled (default) or disabled? Since I got no information on the subject, I'm going to guess that this crash just happened without any player input, and is not the result of trying to spawn a mob/egg.

My suggestion would be to use some world edition software to clear the chunk in question from entities and "untamedwilds:burrow" blocks, since it will be a while until the fix makes its way into a stable release

`Entity's Exact location: 4273.50, 70.00, 9061.50`
`Entity's Block location: World: (4273,70,9061), Section: (at 1,6,5 in 267,4,566; chunk contains blocks 4272,-64,9056 to 4287,319,9071), Region: (8,17; contains chunks 256,544 to 287,575, blocks 4096,-64,8704 to 4607,319,9215)`

I don't have much knowledge in world-edition tools and/or server management, so hopefully these pointers will allow you to temporarily fix it.

**Comment by RayTrace082** [comment]
Added fallback for invalid variants on NBT load, should be fixed
