### ISSUE TITLE
blind cave bear and giant panda doens't spawn naturally

### ISSUE THREAD

**Issue by turkey32** [RayTrace082/untamedwilds#198]
**Describe the bug**

**Steps To Reproduce**

The blind cave bear and panda doens't spawn naturally

**Crash Log**

**Version (please complete the following information):**
 - Minecraft version: [e.g. 1.18.2]
 - Version of the mod: [e.g. 2.2.0]

**Comment by RayTrace082** [comment]
Fixed in-dev

Panda are not bugged, and do spawn very rarely, it's just that Bamboo Forests are small, incredibly cramped, and Panda are competing with Big Cats and Sun Bears for spawn slots. Not like it means much, since Panda aren't really interesting as of now

Underground spawns have been fixed, however

**Comment by ALittleGhazt** [comment]
so does this mean that the blind cave bears and the giant panda spawn naturally?

**Comment by RayTrace082** [comment]
Panda are not bugged, they just happen to be extremely rare because there's many other Apex Predators competing for spawns, and Bamboo forests are awful for mob spawning (Bamboo is everywhere, and any collision blocks spawns). They don't really have any unique feature, so it's very low priority to adress

Underground fauna got broken in 1.18.2, latest version fixes it, so gonna close the issue
