### ISSUE TITLE
Tamed big cats attacks owner

### ISSUE THREAD

**Issue by ZombieChameleon** [RayTrace082/untamedwilds#32]
Not sure if this is a bug or intended, even used the ownership deed on it and it still attacks, it doesn't attack imeditliy but after some time it attacks, it's hunger is full, 200/100 according to the mob analyzer so hunger is not an issue, it has no cubs, it is pregnant but it was attacking before that so that isn't it either.
If this is intended than I understand that, they may be tamed but they are not pets.

**Comment by RayTrace082** [comment]
The ownership deed is only ever useful in Multiplayer, as it's only use is transferring ownership between players

I cannot replicate the issue on my end, tamed mobs have most of their "dangerous" AI goals disabled. Can you post your list of mods? Also, since Big Cats are currently a special case, do other kinds of Big Cat have the same problem?

**Comment by ZombieChameleon** [comment]
@RayTrace082 All big cats have this issue, I have tested every species of it available and every single one did the same thing, I've tried it with other tamable mobs but they don't have the same issue, The only other mod I have installed is Dynamic Surroundings, I've disabled it to see if that was the problem and it wasn't

I also found something else, if another mob has hurts me, the big cats will stop attacking me and start attacking the mob, and than it will go back to being peaceful, and if I have multiple tamed ones, if one attacks me, it kind of starts a war between them until there is one left standing, I may or may not had little fun with this one lol.

**Comment by ZombieChameleon** [comment]
I uploaded this bug onto YouTube, the video is unlisted but should still be visible through this link, hopefully it should give you more information of what's going on.

https://www.youtube.com/watch?v=Uu04CVASDTI

**Comment by RayTrace082** [comment]
Welp, that was really stupid

Basically, it attacks you because you spooked it while it was sleeping, and I am a dunce who forgot to properly check if they are tamed in that one specific instance (Bears have the same behavior, but they properly took that into account)

Thank you for your throughout debugging, it is fixed now for the upcoming version
