### ISSUE TITLE
error server console

### ISSUE THREAD

**Issue by wackoamd1** [RayTrace082/untamedwilds#38]
this is whats filling my console at the start or restart of the server
ain/ERROR] [net.minecraft.entity.ai.attributes.GlobalEntityTypeAttributes/]: Entity untamedwilds:bigcat_dire_lion has no attributes

with every single mob from untamed wilds , bug or ??
i also find very little untamed wilds mobs to be honest but that could be just me

**Comment by RayTrace082** [comment]
That's a bug, but it shouldn't have any negative effect on your game (basically, I forgot to fully disable a bunch of WIP mobs in the release version)

As for the animal density, it is on purpose pretty low, both to make encounters more memorable, and to allow some kind of balance in the world, because predators will eventually kill every other mob. You can change that from the config file, however:

`freqapex = 24`, `freqocean = 16` and `freqcritter = 3` are the parameters you are looking for, and the numbers mean that 1 in X chunks will generate with a random mob of their category (Rhinos and Hippos are considered Apex predators, due to their threat level).

Do note that in the past versions, the frequency for Apex predators was bugged, and lower than what you would expect (it is fixed in the latest version)

**Comment by wackoamd1** [comment]
all your mobs are giving this error , and they just do ot show up in minecraft ;-(
i now installed spawnbalance utility (new mod for mobs) and there isnt even a trace of untamedwilds in the config file , so i guess minecraft doesnt even load/"see" your MOBS (it does put the flora on the world though) which is a shame cause from the  videos ive seen they look great.


little testing done , clean minecraft 1.16.5  , only untamedwilds and SpawnBalanceUtility to check if they are even in minecraft , they just do not register.
flora spawns fine , animals do not get registered anywhere,
