### ISSUE TITLE
Hyenas killing each other?

### ISSUE THREAD

**Issue by Bolushi** [RayTrace082/untamedwilds#46]
I put down around 10 hyenas in an enclosed space, it also had a bunch of bears and big cats, and I immediately noticed the hyenas started fighting each other. I checked to see if species had anything to do with it, but I was spawning the same species. Once there were a bit too many of them they would all fight each other.

**Comment by RayTrace082** [comment]
Can't replicate this one. Hyenas do not attack other Hyena of their same species
Tested with all their assigned Target behaviours (hunger, protecting children, (pack) defense) and none target Hyenas of the same species. 

I did notice a small bug where they checked for Lions, instead of Hyenas, so if there were Lions involved, that may have been the cause. While seemingly harmless, I have fixed it now

**Comment by Bolushi** [comment]
> Can't replicate this one. Hyenas do not attack other Hyena of their same species
> Tested with all their assigned Target behaviours (hunger, protecting children, (pack) defense) and none target Hyenas of the same species.
> 
> I did notice a small bug where they checked for Lions, instead of Hyenas, so if there were Lions involved, that may have been the cause. While seemingly harmless, I have fixed it now

I see. I put a bunch of hyenas of the same species in a globe type deal with lions, bears, tigers, etc. That was probably the issue.
