### ISSUE TITLE
[Compatibility] Entities cannot be instantiated from EntityType

### ISSUE THREAD

**Issue by FlashHUN** [RayTrace082/untamedwilds#53]
Hey there! In my mod, I need to list all living entities registered to the game which I do through an [enum](https://github.com/FlashHUN/FlashNPCs/blob/master/src/main/java/flash/npcmod/core/EntityUtil.java).

However, multiple people have reported that the [game crashes](https://github.com/FlashHUN/FlashNPCs/files/7073019/crash-2021-08-29_20.27.44-server.txt) on world load (when this listing happens) with your mod installed. I think that your entities cannot be instantiated from their type through EntityType#create, though I can't be sure since you know your mod a lot better than I do :D

I'd greatly appreciate if we could achieve compatibility somehow.

**Comment by RayTrace082** [comment]
Damn, that's a really cool mod
This issue is entirely on my end, as there's a couple WIP entities that I register, but do not have attributes nor renderer assigned, so the game crashes trying to make sense of this. Every other mob should be safe to #create
Do you have some sort of blacklist for the enum? If so, the erroring entities will most likely be `untamedwilds:bigcat_cave_lion`, `untamedwilds:bigcat_dire_lion`, `untamedwilds:bigcat_marsupial_lion`, `untamedwilds:bigcat_sabertooth`

Whenever I drop the next update, this should be fixed, since I have properly implemented those mobs

**Comment by FlashHUN** [comment]
> Damn, that's a really cool mod

Thank you!

Yeah, I could blacklist those, but I think people will have to just wait until you release your next update instead. If I blacklist them, that would just mean two featureless updates that do nothing besides adding and removing the blacklist.

**Comment by RayTrace082** [comment]
Should be fixed now
