### ISSUE TITLE
Three bugs

### ISSUE THREAD

**Issue by BlackAures1** [RayTrace082/untamedwilds#56]
1. A single case of a burrow on the water
![image](https://user-images.githubusercontent.com/43911230/132104820-22e9937a-fbe0-483b-b015-d6cf70682c6a.png)

2. An extremely common and most noticeable bug is that all clams appear on the surface and fall down.
![image](https://user-images.githubusercontent.com/43911230/132104851-b877524c-2888-4aa3-9892-4e7dc4c0b050.png)

3. Arowanas spawn in the sky above the water (not in the water) and very often die in the trees because of this.

**Comment by BlackAures1** [comment]
And.. 

![image](https://user-images.githubusercontent.com/43911230/132107633-4c3f17de-2b30-4efe-aa44-2ef04020821d.png)

**Comment by RayTrace082** [comment]
1. Fixed in-dev, the fact that Burrows didn't require a block underneath them was unintended and is now fixed

2. This one is has been a massive pain in the ass, and until now, an intended choice, but it has been fixed in the next version (hopefully, without breaking spawning altogether)

3. This one is mostly intended. To avoid having biomes with a lot of water (eg. Swamps) be devoid of life, I do not prevent (terrestrial) mobs from spawning in Water, so terrestrial mobs will occasionally do so, swim to their nearest landmass and end up stranded on Liliypads. What biome mod is that? because it may just be a case of mis-tagged Biomes, because the Brown/Black Bear + Leopard combo only happens in "Taiga" biomes

**Comment by BlackAures1** [comment]
The point is that they are exactly spawn out on the lilies, not swam there. I was just generating new chunks in creative flight and kept bumping into these creatures.
 _P.s. this problem is number 4 rather. Because in number 3 I wrote about arowanns that die when spawning in foliage._ 

Mod - https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

**Comment by RayTrace082** [comment]
Mobs spawning on lillypads are just seeing it as the closest valid spawn point, and spawning there (when a mob tries to spawn, it will check in multiple directions to ensure a valid spawn), while it looks really dumb, I do not consider it a bug. Mobs are uncommon enough as it is, and I do not consider it fair to players for spawns to be discarded because "lol worldgen"

As for Arowana spawning (and really, all aquatic mobs) that one *should* have been fixed, as the whole spawning algorithm had some massive issues, now they should only spawn within water (do note that they can leap out of the water, this is intended)
