### ISSUE TITLE
just a suggestion 

### ISSUE THREAD

**Issue by titaniumman321** [RayTrace082/untamedwilds#58]
the mammals should have their own unique sounds , personally the throw off in this mod is the fact that rhinos/hippos sound like cows , aardvarks sound like pigs and all the bears/big cats sound the same which doesn't make sense . But other than that , this mod beats other animal mods in every way.

**Comment by RayTrace082** [comment]
Feel free to PR sounds to this repository, because I didn't do that by choice

Royalty-free sound repositories only get you so far when you are looking for obscure animal sounds of consistent quality

I am only looking at exposing the sounds in the sounds.json so they get their own subtitles, and allow players to edit them with a Resource Pack

**Comment by titaniumman321** [comment]
what does PR mean?
