### ISSUE TITLE
question on sound editing

### ISSUE THREAD

**Issue by titaniumman321** [RayTrace082/untamedwilds#60]
so how do I edit the sound of each mob then? Since you cant find obscure animal noises that is of the same level of quality

**Comment by RayTrace082** [comment]
Make a Resource pack overriding the file paths. [Here is the sounds.json where I define the sounds of the mod](https://github.com/RayTrace082/untamedwilds/blob/1.16.3/src/main/resources/assets/untamedwilds/sounds.json). If a sound is not there, it can't be edited. [Here is also the Minecraft wiki article on the format of sounds.json](https://minecraft.fandom.com/wiki/Sounds.json)
For furthr information, look up for tutorials on how to edit sounds, since the process hasn't changed much in recent versions IIRC and is the exact same as in vanilla (just a lot more straightforward, since mods don't use gibberish names)
I do have use a Resource Pack with edited sounds in my own modded instance, so I can confirm that it works

Also, please keep the issue tracker only for issues
