### ISSUE TITLE
1.17 compatibility

### ISSUE THREAD

**Issue by gohkenytp** [RayTrace082/untamedwilds#66]
Is there any way to port this mod to 1.17? Thanks.

**Comment by RayTrace082** [comment]
Not gonna happen. I play on 1.16.5. Maybe I will release a 1.17 build as a stepping stone when porting to the much more interesting 1.18, but don't expect anything

Don't abuse the issue tracker

**Comment by gohkenytp** [comment]
Sorry, I didn't know. It's just that Minecraft suddenly got updated to 1.17 and then 1.18 and you sometimes never cared about my ideas. I just wanna let you understand. Thanks.

**Comment by RayTrace082** [comment]
Apologies for sounding rude. Having people nag about updates gets old fast (this post is the first one that I have not deleted on the spot, since it may get the point across to just tag these as `invalid`)

As for ideas, I don't really take ideas from anyone else. The only exceptions being ideas that polish existing features and inter-mod compatibility (which I sometimes take)
