### ISSUE TITLE
Mob spawn rate adjustment on the config

### ISSUE THREAD

**Issue by DearGodPLS** [RayTrace082/untamedwilds#67]
On the new update mob spawning is insane and its starting to lag the game. I've tinkered around the config and yet the problem still occurs; mobs are everywhere on top of trees and even big cats in the middle of the ocean. please for the love of god do something about this, the game is just unplayable.

**Comment by RayTrace082** [comment]
Do all mobs do that, or is it limited to a specific subset? Are you running additional mods? It works fine on my machine (mobs spawning in trees is an unintended, but known side-effect of allowing mobs to spawn fine in Jungles)

**Comment by DearGodPLS** [comment]
All mobs especially hippos are spawning in extremely large groups. Yes I have additional mods installed.

**Comment by DearGodPLS** [comment]
I've played the mod without any additional mods, and the mob spawning frenzy still persists.

**Comment by RayTrace082** [comment]
Can you provide a screenshot? Also, could you delete the config file 'untamedwilds-common.toml' so it can regenerate back to its default values and see if the issue persists?

As it stands, the default spawn rate for the larger mobs should mean that 1 out of every 24 chunks should have a mob (or a pack, in the case of Hippos, Lions, Hyenas and Boars). This value should be closer to 1 out of 32 due to additional checks and occasional failed spawns

**Comment by DearGodPLS** [comment]
Removing the config file actually fixed the issue! I checked that the old config file had additional lines to fit the mod with the world generation mod that I had previously installed.
