### ISSUE TITLE
Adding variants to tigers

### ISSUE THREAD

**Issue by ReneSopG** [RayTrace082/untamedwilds#77]
Hello, sorry if it bothers, i dont really know where to ask.
I've been trying to add some variants to tigers but i cant make it work. I think the issue its that the tiger texture file from the mod its not numbered like _1, making it impossible to add more.
If thats not the problem i'll put what I tried to do and maybe see if i did it wrong all the time. The resource pack route for the textures its like this "PackName\assets\untamedwilds\textures\entity\big_cat", having his respective packmc.meta
The variant files are named like this "tiger_2.png", i tried to name the first variant "tiger_1.png" but it doesnt work either, adding the default texture "tiger.png" to the pack didnt work either.

Sorry for bad english if something more needs to be explained i can do it.

**Comment by RayTrace082** [comment]
Are you using the latest alpha? If so, you will need to use a datapack to override the [big_cat.json](https://github.com/RayTrace082/untamedwilds/blob/1.16.3/src/main/resources/data/untamedwilds/entities/big_cat.json) file, and add the number of skins for the tiger variant there (check the wiki for more info), alongside all relevant .jpgs in a resource pack

If not using the alpha, Big Cats and Bears are the two exceptions and cannot have new skins added, any skin variation is hardcoded and can't be edited. You did get the process 100% right, however

**Comment by ReneSopG** [comment]
Got it to work, thank you very much!!!! ^^
Like you said, i needed to modify the json file and put it in the pack

**Comment by ReneSopG** [comment]
Two more things, do i have to do something more to make de cubs change skin too?
And, there is a issue that the default skin doesnt apparear, instead a untextured big cat (purple and black colors) apparears. Tried to put the default skin in the data pack, or do the same but putting _1 in the name and still happens.
And by the way, when i try to tame a baby big cat it doesnt eat. I tried without the data pack and stills happens, just to inform ^^

**Comment by RayTrace082** [comment]
The cubs and the parents share the same texture file, so you are editing both by changing the texture, but if you want to give cubs a custom skin, the top-right cluster of textures belongs to them

Basically, if there's one single skin, it will work without a suffix, or with "_1", but if you have multiple skins, then the "_1" on the first one is mandatory. Rare variants need the suffix, no matter how many you have (since the default is zero). If you are getting purple-and-black missing textures, Minecraft *should* complain about it in the log, and tell you the path of the texture it was looking for, this should help you debug if the game thinks there's more skins than the ones present in the files, or what's going on. If you need more help, give me the number of skins you have set, and a list of the skins provided

You can only tame big cat cubs, adults are wild and cannot be tamed. This applies to most mobs

**Comment by ReneSopG** [comment]
Alright, ill work on it later and inform in any result.
And yes, i was trying to tame cubs, i was testing it on egg generated cubs
Thanks for your time!
