### ISSUE TITLE
[alpha-1.5.3] minor inconsistencies and possible bugs

### ISSUE THREAD

**Issue by not-a-squid** [RayTrace082/untamedwilds#91]
**Describe the bug**
there's a few things that i've noticed since updating to 1.5.2 and 1.5.3:

-big cats show up as entity.untamedwilds.big_cat

-entities spawn on top of trees (even in not too dense of forests) or inside of blocks waaay too often and either suffocate or fall to their death

-a lot of spawning inconsistencies that im assuming isn't technically a bug, but more so just how it's set up. like, hyenas spawn so more than big cats despite the config being the same. i don't know if a more detailed config is planned, but i think be very useful for controlling spawns

**Version (please complete the following information):**
 - Minecraft version: 1.16.5
 - Version of the mod: alpha-1.5.3

also, question: could it be possible that the spawns cause potential world gen lag? seeing as they were spawned during world gen, but im not sure if thats how all entities are, or what, but i've noticded my worlds tend to be a bit laggier now

**Comment by RayTrace082** [comment]
>big cats show up as entity.untamedwilds.big_cat

A PR to fix this will be merged when I manage to wrestle with git, and it doesn't really hurt the game anyways

>entities spawn on top of trees (even in not too dense of forests) or inside of blocks waaay too often and either suffocate or fall to their death

Intended, every entity spawning on top of a tree is an entity that wouldn't have spawned otherwise. It's also pretty much mandatory to get mobs spawning in Jungles at all. It does indeed look really stupid, and I am looking at ways to reduce the extent in which it happens

>a lot of spawning inconsistencies that im assuming isn't technically a bug, but more so just how it's set up. like, hyenas spawn so more than big cats despite the config being the same. i don't know if a more detailed config is planned, but i think be very useful for controlling spawns

Both Hyenas and Big Cats have the exact same weight (this value can't currently be edited), so in theory, you should see both in equal measure (per pack! there will be more Hyenas because their packs are simply larger), but mob spawning RNG is screwed, and it tend to spread a few types of mobs throughout a large area. This is a vanilla issue that I do not intend to fix

You can see it in vanilla, you see the same 2-3 types of passive mobs spawning throughout a large area. And I personally like it this way, you can headcanon it as some species having been displaced through competition

>could it be possible that the spawns cause potential world gen lag? seeing as they were spawned during world gen, but im not sure if thats how all entities are, or what, but i've noticed my worlds tend to be a bit laggier now

It wouldn't be surprising, albeit I haven't noticed it, there's a lot of code running behind the scenes when it comes to worldgen. It should go back to vanilla levels once that's done, however (I mean, there's more mobs, and every mob hurts performance a tiny bit, but that's a given)

That is, unless you have enabled natural breeding, and shortened cycles, if you have done both those things, you are going to have an awful time

Gonna close this issue since no new bugs are reported
