### ISSUE TITLE
1.16.5 Wild Animals Following?

### ISSUE THREAD

**Issue by cyanidearsenic** [RayTrace082/untamedwilds#98]
Hi,
I just started looking at a modpack ([Let's Build a ZOO](https://www.curseforge.com/minecraft/modpacks/lets-build-a-zoo-1-0)) in version 1.16.5 and while exploring in peaceful I walked past a mountain lion and a black bear, both asleep, from your mod and now, despite having not interacted with them at all, they are both following me. The mountain lion has been following and shoving into me for at least 500 blocks now and the bear for about half that. I'd rather not kill them to get me to leave me alone but that or going into creative seem to be the only way to make them stop. Is there something wrong with them?
Thanks.

**Comment by RayTrace082** [comment]
Uhhh... I pretty much never took Peaceful mode into account when designing the mod, outside of what vanilla handles (which, to be fair, is most things), chances are this is the case for the sleep aggression behavior, so the mob will chase you, trying to attack you, but the attacks can't happen, because the world is on Peaceful

You can probably avoid this issue entirely by setting the 'angry_sleepers' parameter to false in the config file until I fix it (you won't miss anything, since sleep aggression only triggers against players)
