### ISSUE TITLE
Version Question

### ISSUE THREAD

**Issue by LidorPrototype** [RayTrace082/untamedwilds#99]
Will this be supported on version 1.18.1?

**Comment by LidorPrototype** [comment]
Can you at least explain why you closed it without a statement beside labeling it as invalid?
@RayTrace082

**Comment by RayTrace082** [comment]
Because you don't care enough to check the templates

> *Before submitting a feature request, be warned, suggestions relating to version changes and/or additional mobs will be deleted. Please, delete this disclaimer before submitting a feature request*

But given that I never disabled blank issues, there's a chance it never popped up

Yes. I have been working on 1.18 for a while, but given that sub-versions were guaranteed to happen, I have been taking the time to improve some textures, and clean up some of the code. There will probably be nothing for 1.18.1, and since there's a chance we are getting another 1.16.3 shitshow with 1.18.2, I'd rather wait instead of supporting two 1.18.X versions
